version: "3.8"

services:
  database:
    image: "postgres:alpine3.18"
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data

  node:
    container_name: yourney-be
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8001:3000
    entrypoint: ./start.sh
    # command: tail -F /dev/null



